### ISSUE TITLE
The python version should be 3.x ?

### ISSUE THREAD

**Issue by gzhcv** [jxgu1016/Gabor_CNN_PyTorch#12]
Hi, due to that the division operation is different between python 2.x and python 3.x, there is some 
incorrectly code of  division operation if python 2.x is used. For example, line 107 of `GConv.py`, the
`theta` would be 0 for all filter. Hope you could mention the python version in README.

**Comment by jxgu1016** [comment]
@gzhcv Thanks for you kind advise. Since I am quite busy these days, I will fix this issue later.

**Comment by gzhcv** [comment]
@jxgu1016  Thanks! I just no sure if this is a issue,  because i visualized the filter in GoFs and find it seems each filter is different with others. 

- For the filters of first layer,  in the beginning training stage, the filters obtained by modulating a learned convolutional filter using different orientation Gabor filters are different with each other.

![微信图片_20190616101148](https://user-images.githubusercontent.com/19361578/59591913-86060300-9121-11e9-8d61-9ca3fe7f6717.png)

But after training for 0.x million steps ,  the filters are quite similar to each other (see the following figure), but actually the values are different. 

![微信图片_20190615234400](https://user-images.githubusercontent.com/19361578/59591541-c4e78900-9120-11e9-89a0-bd22a9100819.png)

- For the filters of second layer,  the filters are different to each other even training for  0.x million steps.

So, it seems this is not a issue. I just not very clear about how the GConv.py is used for build the Python package.

**Comment by jxgu1016** [comment]
Thanks for your detailed report,  and I will check it later.

**Comment by jxgu1016** [comment]
@gzhcv My python version is 2.7.  There should be some 0 in the filters. It  seems not to be a issue. Thx for your report anyway.

**Comment by gzhcv** [comment]
@jxgu1016  The parameter `theta ` represents different orientation of Gabor filter, if the GoF is obtained by the code in `GConv.py` (since `theta ` is always be 0 that computed in line 107 of GConv.py), why the learned filters are different with each other?  I'm confused about this.

**Comment by jxgu1016** [comment]
@gzhcv you may miss the codes on the 1st line: ```from __future__ import division```.

**Comment by gzhcv** [comment]
@jxgu1016 Oh....  Sorry for my carelessness.
