### ISSUE TITLE
Test on cifar10 didn't achieve the result in the paper.

### ISSUE THREAD

**Issue by AManFromEarth** [jxgu1016/Gabor_CNN_PyTorch#2]
I used your Gabor CNN on the cifar10, but didn't get the result in the paper showed.

**Comment by jxgu1016** [comment]
More specifically please.

**Comment by jxgu1016** [comment]
There must be something wrong with your codes. For GCN4-40 (16-32-64-128, 8.9M), I got a error at 4.22%  which is less than what reported in the paper (4.65%).

**Comment by AManFromEarth** [comment]
Maybe you are right.In the beginning I thought there must be something wrong in my code,too.But I couldn't find where the problem is .Could you open your cifar10 code?Or just sent me?I would be very grateful!Thank you!

**Comment by jxgu1016** [comment]
Sorry, it's not my paper, so cifar10 codes cannot open source according to the authors.

**Comment by AManFromEarth** [comment]
Ummm, I tried contact with the author ,but he didn't response.And could you send me the code?My email is liuwenjun6146@163.com.
