### ISSUE TITLE
Error occur whern type "sh install.sh"

### ISSUE THREAD

**Issue by ymcasky** [jxgu1016/Gabor_CNN_PyTorch#3]
Dear jxgu1016,

Sorry for bothering.
Here is my system :
 **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
 **Pytorch installed from (source or binary)**: conda install pytorch torchvision cuda90 -c pytorch
 **GCC/Compiler version (if compiling from source)**: gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
 **CUDA/cuDNN version**: cuda9.0 / cuDNN7.0.5
 **GPU model and memory**: Nvidia 1070

When I type "sh install.sh"
The message show : 

Compiling cuda kernels...
rm: 無法移除 'libgcn_kernel.cu.o': 沒有此一檔案或目錄
In file included from /usr/local/cuda-9.0/bin/../targets/x86_64-linux/include/host_config.h:50:0,
                 from /usr/local/cuda-9.0/bin/../targets/x86_64-linux/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/local/cuda-9.0/bin/../targets/x86_64-linux/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
Installing extension...
Including CUDA code.
running clean
removing 'build/temp.linux-x86_64-3.5' (and everything under it)
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fee058d3ae8>
Traceback (most recent call last):
  File "/home/luojiewei/anaconda3/envs/tf35/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Including CUDA code.
running install
running bdist_egg
running egg_info
writing requirements to gcn.egg-info/requires.txt
writing top-level names to gcn.egg-info/top_level.txt
writing gcn.egg-info/PKG-INFO
writing dependency_links to gcn.egg-info/dependency_links.txt
reading manifest file 'gcn.egg-info/SOURCES.txt'
writing manifest file 'gcn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying gcn/_ext/libgcn/__init__.py -> build/lib.linux-x86_64-3.5/gcn/_ext/libgcn
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.5/gcn._ext.libgcn._libgcn.c'
creating build/temp.linux-x86_64-3.5
building 'gcn._ext.libgcn._libgcn' extension
creating build/temp.linux-x86_64-3.5/build
creating build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/media
creating build/temp.linux-x86_64-3.5/media/luojiewei
creating build/temp.linux-x86_64-3.5/media/luojiewei/70303F89D6F80E5A
creating build/temp.linux-x86_64-3.5/media/luojiewei/70303F89D6F80E5A/code
creating build/temp.linux-x86_64-3.5/media/luojiewei/70303F89D6F80E5A/code/DL
creating build/temp.linux-x86_64-3.5/media/luojiewei/70303F89D6F80E5A/code/DL/RotateInv
creating build/temp.linux-x86_64-3.5/media/luojiewei/70303F89D6F80E5A/code/DL/RotateInv/Gabor_CNN_PyTorch-master
creating build/temp.linux-x86_64-3.5/media/luojiewei/70303F89D6F80E5A/code/DL/RotateInv/Gabor_CNN_PyTorch-master/gcn
creating build/temp.linux-x86_64-3.5/media/luojiewei/70303F89D6F80E5A/code/DL/RotateInv/Gabor_CNN_PyTorch-master/gcn/src
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -fPIC -DWITH_CUDA -I/home/luojiewei/anaconda3/envs/tf35/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include -I/home/luojiewei/anaconda3/envs/tf35/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/luojiewei/anaconda3/envs/tf35/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -Igcn/src -I/home/luojiewei/anaconda3/envs/tf35/include/python3.5m -c build/temp.linux-x86_64-3.5/gcn._ext.libgcn._libgcn.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/gcn._ext.libgcn._libgcn.o -fopenmp
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -fPIC -DWITH_CUDA -I/home/luojiewei/anaconda3/envs/tf35/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include -I/home/luojiewei/anaconda3/envs/tf35/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/luojiewei/anaconda3/envs/tf35/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -Igcn/src -I/home/luojiewei/anaconda3/envs/tf35/include/python3.5m -c /media/luojiewei/70303F89D6F80E5A/code/DL/RotateInv/Gabor_CNN_PyTorch-master/gcn/src/libgcn.c -o build/temp.linux-x86_64-3.5/media/luojiewei/70303F89D6F80E5A/code/DL/RotateInv/Gabor_CNN_PyTorch-master/gcn/src/libgcn.o -fopenmp
In file included from generic/GaborOrientationFilter.c:1:0,
                 from /home/luojiewei/anaconda3/envs/tf35/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateFloatTypes.h:10,
                 from /media/luojiewei/70303F89D6F80E5A/code/DL/RotateInv/Gabor_CNN_PyTorch-master/gcn/src/libgcn.c:12:
gcn/src/generic/GaborOrientationFilter.c: In function ‘gcn_Float_GOF_Producing’:
gcn/src/generic/GaborOrientationFilter.c:29:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (l = 0; l < nChannel * kH * kW; l++) {
                           ^
In file included from generic/GaborOrientationFilter.c:1:0,
                 from /home/luojiewei/anaconda3/envs/tf35/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH/THGenerateFloatTypes.h:11,
                 from /media/luojiewei/70303F89D6F80E5A/code/DL/RotateInv/Gabor_CNN_PyTorch-master/gcn/src/libgcn.c:12:
gcn/src/generic/GaborOrientationFilter.c: In function ‘gcn_Double_GOF_Producing’:
gcn/src/generic/GaborOrientationFilter.c:29:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (l = 0; l < nChannel * kH * kW; l++) {
                           ^
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -fPIC -DWITH_CUDA -I/home/luojiewei/anaconda3/envs/tf35/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include -I/home/luojiewei/anaconda3/envs/tf35/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/luojiewei/anaconda3/envs/tf35/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -Igcn/src -I/home/luojiewei/anaconda3/envs/tf35/include/python3.5m -c /media/luojiewei/70303F89D6F80E5A/code/DL/RotateInv/Gabor_CNN_PyTorch-master/gcn/src/libgcn_cuda.c -o build/temp.linux-x86_64-3.5/media/luojiewei/70303F89D6F80E5A/code/DL/RotateInv/Gabor_CNN_PyTorch-master/gcn/src/libgcn_cuda.o -fopenmp
gcc -pthread -shared -L/home/luojiewei/anaconda3/envs/tf35/lib -Wl,-rpath=/home/luojiewei/anaconda3/envs/tf35/lib,--no-as-needed build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/gcn._ext.libgcn._libgcn.o build/temp.linux-x86_64-3.5/media/luojiewei/70303F89D6F80E5A/code/DL/RotateInv/Gabor_CNN_PyTorch-master/gcn/src/libgcn.o build/temp.linux-x86_64-3.5/media/luojiewei/70303F89D6F80E5A/code/DL/RotateInv/Gabor_CNN_PyTorch-master/gcn/src/libgcn_cuda.o gcn/src/libgcn_kernel.cu.o -L/home/luojiewei/anaconda3/envs/tf35/lib -lpython3.5m -o build/lib.linux-x86_64-3.5/gcn/_ext/libgcn/_libgcn.abi3.so
gcc: error: gcn/src/libgcn_kernel.cu.o: 沒有此一檔案或目錄
error: command 'gcc' failed with exit status 1

Can you tell me  how to fix it?
Many thanks!!

**Comment by jxgu1016** [comment]
Hi!
Obviously, downgrade your gcc version as is shown in the errors "error:
#error -- unsupported GNU version! gcc versions later than 6 are not
supported!
#error -- unsupported GNU version! gcc versions later than 6 are not
supported!"


2018-05-23 14:18 GMT+08:00 ymcasky <notifications@github.com>:

**Comment by ymcasky** [comment]
Hi, thanks for your reply :)
I think this is somehow system error because it still occur when I downgrade gcc to 5.5 version.
I directly downgrade ubuntu18.04 to 16.04.
It work properly!  : )
