### ISSUE TITLE
How to see the model

### ISSUE THREAD

**Issue by ymcasky** [jxgu1016/Gabor_CNN_PyTorch#4]
Hi,

How can I see the model after using "visualize_graph(model, writer, input_size=(1, 1, 28, 28))"
There are many log in demo/runs/May23xxxx
Thanks for your help!!

**Comment by jxgu1016** [comment]
Please refer to [tensorboardX](https://github.com/lanpa/tensorboard-pytorch).

**Comment by jxgu1016** [comment]
That is to say
```tensorboard --logdir runs```

**Comment by ymcasky** [comment]
Thanks for your reply.
I will ask after I google it next time.
I already familiar with tensorflow but new to pytorch.
So good to see pytorch can see the model as tensorflow!
