### ISSUE TITLE
Error occur when run gcn/modules/Gconv.py

### ISSUE THREAD

**Issue by ymcasky** [jxgu1016/Gabor_CNN_PyTorch#5]
When I run gcn/modules/Gconv.py

I modify the following : 
1.) line 9
from .utils import _pair ->  from utils import _pair
2.) line 64
for i in range(bias.size()): ->  for i in range(bias.size()[0]):

But it still have error in line 67 which show error message
NameError: global name 'x' is not defined

Can you tell me how to fix it?  Thanks!

**Comment by jxgu1016** [comment]
1. There is a typo in line 67 and now fixed, please download the latest codes.
2. Your modification
1): may cause error
2): the return of torch.size() has changed in PyTorch 0.4, so your modification looks right.

**Comment by ymcasky** [comment]
Thanks for your reply!
I will try it :)
