### ISSUE TITLE
 error: dereferencing pointer to incomplete type ‘THTensor {aka struct THTensor}’

### ISSUE THREAD

**Issue by cq41406369** [jxgu1016/Gabor_CNN_PyTorch#8]
When I followed the instruction of ReadMe, something occurred in the ¨sh install.sh¨ command.Here is the information:
`Compiling cuda kernels...
rm: 无法删除'libgcn_kernel.cu.o': 没有那个文件或目录
Installing extension...
Including CUDA code.
running clean
removing 'build/temp.linux-x86_64-3.5' (and everything under it)
Including CUDA code.
running install
Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python3.5/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing dependency_links to gcn.egg-info/dependency_links.txt
writing top-level names to gcn.egg-info/top_level.txt
writing requirements to gcn.egg-info/requires.txt
writing gcn.egg-info/PKG-INFO
reading manifest file 'gcn.egg-info/SOURCES.txt'
writing manifest file 'gcn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying gcn/_ext/libgcn/__init__.py -> build/lib.linux-x86_64-3.5/gcn/_ext/libgcn
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.5/gcn._ext.libgcn._libgcn.c'
creating build/temp.linux-x86_64-3.5
building 'gcn._ext.libgcn._libgcn' extension
creating build/temp.linux-x86_64-3.5/build
creating build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/home
creating build/temp.linux-x86_64-3.5/home/Gabor_CNN_PyTorch
creating build/temp.linux-x86_64-3.5/home/Gabor_CNN_PyTorch/gcn
creating build/temp.linux-x86_64-3.5/home/Gabor_CNN_PyTorch/gcn/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -Igcn/src -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/gcn._ext.libgcn._libgcn.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/gcn._ext.libgcn._libgcn.o -std=c99 -fopenmp
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -Igcn/src -I/usr/include/python3.5m -c /home/Gabor_CNN_PyTorch/gcn/src/libgcn.c -o build/temp.linux-x86_64-3.5/home/Gabor_CNN_PyTorch/gcn/src/libgcn.o -std=c99 -fopenmp
In file included from /usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/TH/TH.h:4:0,
                 from /home/Gabor_CNN_PyTorch/gcn/src/libgcn.c:1:
gcn/src/generic/GaborOrientationFilter.c: In function ‘gcn_Float_GOF_Producing’:
gcn/src/generic/GaborOrientationFilter.c:10:22: error: dereferencing pointer to incomplete type ‘THTensor {aka struct THTensor}’
     THArgCheck(weight->nDimension == 5, 1, "only supports a batch of GOFs.");
                      ^
/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:111:35: note: in definition of macro ‘THArgCheck’
   _THArgCheck(__FILE__, __LINE__, __VA_ARGS__);                       \
                                   ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

Do you know why this happens?Thank you!

**Comment by jxgu1016** [comment]
PyTorch version?

**Comment by cq41406369** [comment]
Ubuntu 16.04, Pytorch 4.1,CUDA 9.2,Cudnn 7.2

**Comment by jxgu1016** [comment]
try to downgrade pytorch to 0.4 or earlier

**Comment by cq41406369** [comment]
OK,I'll do it.Thank you!

**Comment by Pongroc** [comment]
> OK,I'll do it.Thank you!

Hi , i met the same problem as yours, have you solved the problem by downgrading the version of pytorch ?

**Comment by Pongroc** [comment]
@cq41406369
